#!/bin/bash

echo "Setting up local domain for OAuth development..."
echo ""
echo "This script will add a local domain that points to your machine's IP address."
echo "This is needed because Google OAuth doesn't allow IP addresses."
echo ""
echo "Please run the following command manually:"
echo ""
echo "sudo sh -c 'echo \"192.168.100.18 local.agrotrade.dev\" >> /etc/hosts'"
echo ""
echo "After adding this, you can use:"
echo "- http://local.agrotrade.dev:4000 for backend"
echo "- http://local.agrotrade.dev:8081 for frontend"
echo ""
echo "Then add this to Google OAuth console:"
echo "http://local.agrotrade.dev:4000/api/auth/google/callback"