import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  createMint,
  createAccount,
  mintTo,
  getAccount,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";

// Type will be generated by `anchor build`
// For now we use any — the IDL is auto-generated
type AgroEscrow = any;

describe("agro-escrow", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.AgroEscrow as Program<AgroEscrow>;

  // Keypairs
  const admin = provider.wallet as anchor.Wallet;
  const buyer = anchor.web3.Keypair.generate();
  const seller = anchor.web3.Keypair.generate();
  const newAdmin = anchor.web3.Keypair.generate();

  // Token mint + accounts
  let mint: anchor.web3.PublicKey;
  let buyerTokenAccount: anchor.web3.PublicKey;
  let sellerTokenAccount: anchor.web3.PublicKey;
  let newAdminTokenAccount: anchor.web3.PublicKey;

  // PDAs
  let configPda: anchor.web3.PublicKey;
  let configBump: number;

  const TRADE_ID = "trade-001";
  const TRADE_ID_2 = "trade-002";
  const TRADE_ID_3 = "trade-003";
  const ESCROW_AMOUNT = 1_000_000; // 1 USDC (6 decimals)

  // Helper: derive escrow PDA
  function getEscrowPda(tradeId: string) {
    return anchor.web3.PublicKey.findProgramAddressSync(
      [Buffer.from("escrow"), Buffer.from(tradeId)],
      program.programId
    );
  }

  // Helper: derive vault PDA
  function getVaultPda(escrowPda: anchor.web3.PublicKey) {
    return anchor.web3.PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), escrowPda.toBuffer()],
      program.programId
    );
  }

  before(async () => {
    // Airdrop SOL to buyer, seller, newAdmin for fees
    const airdropAmount = 10 * anchor.web3.LAMPORTS_PER_SOL;
    await Promise.all([
      provider.connection
        .requestAirdrop(buyer.publicKey, airdropAmount)
        .then((sig) => provider.connection.confirmTransaction(sig)),
      provider.connection
        .requestAirdrop(seller.publicKey, airdropAmount)
        .then((sig) => provider.connection.confirmTransaction(sig)),
      provider.connection
        .requestAirdrop(newAdmin.publicKey, airdropAmount)
        .then((sig) => provider.connection.confirmTransaction(sig)),
    ]);

    // Create USDC-like mint (6 decimals)
    mint = await createMint(
      provider.connection,
      (admin as any).payer,
      admin.publicKey,
      null,
      6
    );

    // Create token accounts
    buyerTokenAccount = await createAccount(
      provider.connection,
      (admin as any).payer,
      mint,
      buyer.publicKey
    );
    sellerTokenAccount = await createAccount(
      provider.connection,
      (admin as any).payer,
      mint,
      seller.publicKey
    );
    newAdminTokenAccount = await createAccount(
      provider.connection,
      (admin as any).payer,
      mint,
      newAdmin.publicKey
    );

    // Mint 100 USDC to buyer
    await mintTo(
      provider.connection,
      (admin as any).payer,
      mint,
      buyerTokenAccount,
      admin.publicKey,
      100_000_000 // 100 USDC
    );

    // Derive config PDA
    [configPda, configBump] = anchor.web3.PublicKey.findProgramAddressSync(
      [Buffer.from("config")],
      program.programId
    );
  });

  // ─── Initialize ───────────────────────────────────────────────

  it("initializes the config with deployer as admin", async () => {
    await program.methods
      .initialize()
      .accounts({
        config: configPda,
        authority: admin.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .rpc();

    const config = await program.account.config.fetch(configPda);
    assert.ok(config.admin.equals(admin.publicKey));
    assert.ok(config.pendingAdmin.equals(anchor.web3.PublicKey.default));
  });

  // ─── Admin Transfer ───────────────────────────────────────────

  it("nominates a new admin", async () => {
    await program.methods
      .nominateAdmin(newAdmin.publicKey)
      .accounts({
        config: configPda,
        admin: admin.publicKey,
      })
      .rpc();

    const config = await program.account.config.fetch(configPda);
    assert.ok(config.pendingAdmin.equals(newAdmin.publicKey));
  });

  it("rejects nominate from non-admin", async () => {
    try {
      await program.methods
        .nominateAdmin(buyer.publicKey)
        .accounts({
          config: configPda,
          admin: buyer.publicKey,
        })
        .signers([buyer])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "Unauthorized");
    }
  });

  it("pending admin accepts the role", async () => {
    await program.methods
      .acceptAdmin()
      .accounts({
        config: configPda,
        newAdmin: newAdmin.publicKey,
      })
      .signers([newAdmin])
      .rpc();

    const config = await program.account.config.fetch(configPda);
    assert.ok(config.admin.equals(newAdmin.publicKey));
    assert.ok(config.pendingAdmin.equals(anchor.web3.PublicKey.default));
  });

  it("transfers admin back to original for remaining tests", async () => {
    // newAdmin nominates original admin back
    await program.methods
      .nominateAdmin(admin.publicKey)
      .accounts({
        config: configPda,
        admin: newAdmin.publicKey,
      })
      .signers([newAdmin])
      .rpc();

    await program.methods
      .acceptAdmin()
      .accounts({
        config: configPda,
        newAdmin: admin.publicKey,
      })
      .rpc();

    const config = await program.account.config.fetch(configPda);
    assert.ok(config.admin.equals(admin.publicKey));
  });

  // ─── Create Escrow ────────────────────────────────────────────

  it("creates an escrow and locks USDC", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID);
    const [vaultPda] = getVaultPda(escrowPda);

    const buyerBefore = await getAccount(provider.connection, buyerTokenAccount);

    await program.methods
      .createEscrow(TRADE_ID, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    // Verify escrow state
    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.ok(escrow.buyer.equals(buyer.publicKey));
    assert.ok(escrow.seller.equals(seller.publicKey));
    assert.equal(escrow.amount.toNumber(), ESCROW_AMOUNT);
    assert.deepEqual(escrow.state, { awaitingDelivery: {} });
    assert.equal(escrow.tradeId, TRADE_ID);

    // Verify USDC transferred to vault
    const vault = await getAccount(provider.connection, vaultPda);
    assert.equal(Number(vault.amount), ESCROW_AMOUNT);

    const buyerAfter = await getAccount(provider.connection, buyerTokenAccount);
    assert.equal(
      Number(buyerBefore.amount) - Number(buyerAfter.amount),
      ESCROW_AMOUNT
    );
  });

  it("rejects zero-amount escrow", async () => {
    const [escrowPda] = getEscrowPda("trade-zero");
    const [vaultPda] = getVaultPda(escrowPda);

    try {
      await program.methods
        .createEscrow("trade-zero", new anchor.BN(0))
        .accounts({
          escrow: escrowPda,
          vault: vaultPda,
          mint,
          buyerTokenAccount,
          buyer: buyer.publicKey,
          seller: seller.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: anchor.web3.SystemProgram.programId,
          rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        })
        .signers([buyer])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "ZeroAmount");
    }
  });

  // ─── Release Funds ────────────────────────────────────────────

  it("buyer releases funds to seller", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID);
    const [vaultPda] = getVaultPda(escrowPda);

    const sellerBefore = await getAccount(
      provider.connection,
      sellerTokenAccount
    );

    await program.methods
      .releaseFunds()
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        sellerTokenAccount,
        config: configPda,
        authority: buyer.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([buyer])
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { complete: {} });
    assert.equal(escrow.amount.toNumber(), 0);

    const sellerAfter = await getAccount(
      provider.connection,
      sellerTokenAccount
    );
    assert.equal(
      Number(sellerAfter.amount) - Number(sellerBefore.amount),
      ESCROW_AMOUNT
    );
  });

  it("rejects release on already-completed escrow", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID);
    const [vaultPda] = getVaultPda(escrowPda);

    try {
      await program.methods
        .releaseFunds()
        .accounts({
          escrow: escrowPda,
          vault: vaultPda,
          sellerTokenAccount,
          config: configPda,
          authority: buyer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidState");
    }
  });

  // ─── Dispute Flow ─────────────────────────────────────────────

  it("creates a second escrow for dispute testing", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID_2);
    const [vaultPda] = getVaultPda(escrowPda);

    await program.methods
      .createEscrow(TRADE_ID_2, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();
  });

  it("buyer raises a dispute", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID_2);

    await program.methods
      .raiseDispute()
      .accounts({
        escrow: escrowPda,
        config: configPda,
        authority: buyer.publicKey,
      })
      .signers([buyer])
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { disputed: {} });
  });

  it("rejects dispute on non-AWAITING_DELIVERY escrow", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID_2);

    try {
      await program.methods
        .raiseDispute()
        .accounts({
          escrow: escrowPda,
          config: configPda,
          authority: buyer.publicKey,
        })
        .signers([buyer])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidState");
    }
  });

  it("admin resolves dispute in favor of seller", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID_2);
    const [vaultPda] = getVaultPda(escrowPda);

    const sellerBefore = await getAccount(
      provider.connection,
      sellerTokenAccount
    );

    await program.methods
      .resolveDispute(false) // release to seller
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        recipientTokenAccount: sellerTokenAccount,
        config: configPda,
        admin: admin.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { complete: {} });
    assert.equal(escrow.amount.toNumber(), 0);

    const sellerAfter = await getAccount(
      provider.connection,
      sellerTokenAccount
    );
    assert.equal(
      Number(sellerAfter.amount) - Number(sellerBefore.amount),
      ESCROW_AMOUNT
    );
  });

  it("rejects resolve from non-admin", async () => {
    // Create + dispute a third escrow
    const [escrowPda] = getEscrowPda(TRADE_ID_3);
    const [vaultPda] = getVaultPda(escrowPda);

    await program.methods
      .createEscrow(TRADE_ID_3, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    await program.methods
      .raiseDispute()
      .accounts({
        escrow: escrowPda,
        config: configPda,
        authority: buyer.publicKey,
      })
      .signers([buyer])
      .rpc();

    try {
      await program.methods
        .resolveDispute(true)
        .accounts({
          escrow: escrowPda,
          vault: vaultPda,
          recipientTokenAccount: buyerTokenAccount,
          config: configPda,
          admin: buyer.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([buyer])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "Unauthorized");
    }
  });

  // ─── Refund Flow ──────────────────────────────────────────────

  it("admin refunds buyer from disputed escrow", async () => {
    const [escrowPda] = getEscrowPda(TRADE_ID_3);
    const [vaultPda] = getVaultPda(escrowPda);

    const buyerBefore = await getAccount(
      provider.connection,
      buyerTokenAccount
    );

    await program.methods
      .refund()
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        buyerTokenAccount,
        config: configPda,
        admin: admin.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { refunded: {} });
    assert.equal(escrow.amount.toNumber(), 0);

    const buyerAfter = await getAccount(
      provider.connection,
      buyerTokenAccount
    );
    assert.equal(
      Number(buyerAfter.amount) - Number(buyerBefore.amount),
      ESCROW_AMOUNT
    );
  });

  it("rejects refund from non-admin", async () => {
    // Trade 3 is already refunded — this should fail on state check anyway
    const [escrowPda] = getEscrowPda(TRADE_ID_3);
    const [vaultPda] = getVaultPda(escrowPda);

    try {
      await program.methods
        .refund()
        .accounts({
          escrow: escrowPda,
          vault: vaultPda,
          buyerTokenAccount,
          config: configPda,
          admin: seller.publicKey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([seller])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      // Could be Unauthorized or InvalidState — either is correct
      assert.ok(
        e.toString().includes("Unauthorized") ||
          e.toString().includes("InvalidState")
      );
    }
  });

  // ─── Admin release ────────────────────────────────────────────

  it("admin can release funds on behalf of buyer", async () => {
    const tradeId = "trade-admin-release";
    const [escrowPda] = getEscrowPda(tradeId);
    const [vaultPda] = getVaultPda(escrowPda);

    await program.methods
      .createEscrow(tradeId, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    const sellerBefore = await getAccount(
      provider.connection,
      sellerTokenAccount
    );

    // Admin (not buyer) releases
    await program.methods
      .releaseFunds()
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        sellerTokenAccount,
        config: configPda,
        authority: admin.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { complete: {} });

    const sellerAfter = await getAccount(
      provider.connection,
      sellerTokenAccount
    );
    assert.equal(
      Number(sellerAfter.amount) - Number(sellerBefore.amount),
      ESCROW_AMOUNT
    );
  });

  // ─── Seller raises dispute ────────────────────────────────────

  it("seller can raise a dispute", async () => {
    const tradeId = "trade-seller-dispute";
    const [escrowPda] = getEscrowPda(tradeId);
    const [vaultPda] = getVaultPda(escrowPda);

    await program.methods
      .createEscrow(tradeId, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    await program.methods
      .raiseDispute()
      .accounts({
        escrow: escrowPda,
        config: configPda,
        authority: seller.publicKey,
      })
      .signers([seller])
      .rpc();

    const escrow = await program.account.escrow.fetch(escrowPda);
    assert.deepEqual(escrow.state, { disputed: {} });
  });

  // ─── Unauthorized release ─────────────────────────────────────

  it("random user cannot release funds", async () => {
    const tradeId = "trade-unauth-release";
    const [escrowPda] = getEscrowPda(tradeId);
    const [vaultPda] = getVaultPda(escrowPda);

    await program.methods
      .createEscrow(tradeId, new anchor.BN(ESCROW_AMOUNT))
      .accounts({
        escrow: escrowPda,
        vault: vaultPda,
        mint,
        buyerTokenAccount,
        buyer: buyer.publicKey,
        seller: seller.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .signers([buyer])
      .rpc();

    try {
      await program.methods
        .releaseFunds()
        .accounts({
          escrow: escrowPda,
          vault: vaultPda,
          sellerTokenAccount,
          config: configPda,
          authority: seller.publicKey, // seller can't release
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([seller])
        .rpc();
      assert.fail("Should have thrown");
    } catch (e: any) {
      assert.include(e.toString(), "Unauthorized");
    }
  });
});
