import { StyleSheet } from 'react-native';

import { COLORS } from '@design-system';

export const styles = StyleSheet.create({
  closeBtn: { padding: 4 },
  content: { flex: 1 },
  fieldGroup: { marginBottom: 12 },
  fieldLabel: {
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  fieldValue: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '600' },
  footer: { margin: 16, marginTop: 8 },
  footerBtn: {},
  footerBtnFlex: { flex: 1 },
  footerButtons: { flexDirection: 'row', gap: 12 },
  goldPrice: {
    color: COLORS.accentGold,
    fontFamily: 'monospace',
    fontSize: 14,
    fontWeight: '700',
  },
  halfField: { flex: 1 },
  header: { borderRadius: 14, margin: 16, marginBottom: 8 },
  headerRow: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  headerSub: { color: COLORS.textSecondary, fontSize: 12, marginTop: 2 },
  headerText: { flex: 1 },
  headerTitle: { color: COLORS.textPrimary, fontSize: 18, fontWeight: '800' },
  hintText: { color: COLORS.textMuted, fontSize: 11, marginBottom: 4 },
  infoBody: { color: COLORS.textSecondary, fontSize: 12, lineHeight: 18 },
  infoLabel: { fontSize: 12, fontWeight: '700', marginBottom: 4 },
  loaderCenter: {
    alignItems: 'center',
    flex: 1,
    gap: 10,
    justifyContent: 'center',
    paddingVertical: 48,
  },
  loaderText: { color: COLORS.textSecondary, fontSize: 13 },
  locationRow: { alignItems: 'center', flexDirection: 'row', gap: 4, marginTop: 3 },
  locationText: { color: COLORS.textMuted, fontSize: 11 },
  metaLabel: { color: COLORS.textSecondary, fontSize: 12 },
  metaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  metaValue: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '600' },
  progressBar: { borderRadius: 3, height: '100%' },
  progressBg: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 3,
    height: 6,
    overflow: 'hidden',
  },
  progressTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  root: { backgroundColor: 'transparent', flex: 1 },
  rowFields: { flexDirection: 'row', gap: 16, marginBottom: 12 },
  sellerAvailable: { color: COLORS.textSecondary, fontSize: 12, marginBottom: 4 },
  sellerBottomRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  sellerHeader: { padding: 16, paddingBottom: 8 },
  sellerList: { flex: 1, paddingHorizontal: 16 },
  sellerName: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '700' },
  sellerNameCol: { flex: 1, marginRight: 8 },
  sellerTaking: { fontSize: 12, fontWeight: '600', marginBottom: 4 },
  sellerTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  sendOfferBtn: {
    backgroundColor: 'rgba(96,165,250,0.2)',
    borderColor: 'rgba(96,165,250,0.4)',
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  sendOfferBtnText: { color: COLORS.info, fontSize: 11, fontWeight: '700' },
  stepActive: { backgroundColor: COLORS.accentGreen },
  stepBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  stepCircle: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    marginBottom: 4,
    width: 28,
  },
  stepCompleted: { backgroundColor: COLORS.info },
  stepContent: { flex: 1, padding: 16 },
  stepContentFull: { flex: 1 },
  stepItem: { alignItems: 'center', flex: 1, flexDirection: 'row', justifyContent: 'center' },
  stepLabel: { color: COLORS.textMuted, fontSize: 10, marginHorizontal: 6 },
  stepLabelActive: { color: COLORS.textPrimary, fontWeight: '700' },
  stepTitle: { color: COLORS.textPrimary, fontSize: 16, fontWeight: '800', marginBottom: 12 },
  subSectionLabel: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '700', marginBottom: 8 },
  transportDetails: { flex: 1, padding: 16 },
});
