import { StyleSheet } from 'react-native';

const GREEN = '#4ADE80';
const GREEN_BG = 'rgba(74,222,128,0.12)';
const GREEN_BORDER = 'rgba(74,222,128,0.4)';
const GLASS_BG = 'rgba(255,255,255,0.05)';
const GLASS_BORDER = 'rgba(255,255,255,0.09)';

export { GREEN, GREEN_BG, GREEN_BORDER, GLASS_BG, GLASS_BORDER };

export const styles = StyleSheet.create({
  addBtn: {
    alignItems: 'center',
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 16,
    paddingVertical: 15,
  },
  addBtnDisabled: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderColor: 'rgba(255,255,255,0.08)',
  },
  addBtnText: {
    color: GREEN,
    fontSize: 15,
    fontWeight: '700',
  },
  addBtnTextDisabled: {
    color: 'rgba(255,255,255,0.25)',
  },
  cancelText: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
    textAlign: 'center',
  },
  capacityBtn: {
    alignItems: 'center',
    backgroundColor: GLASS_BG,
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 8,
    paddingVertical: 14,
    width: '31%',
  },
  capacityBtnActive: {
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
  },
  capacityBtnNum: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 18,
    fontWeight: '800',
  },
  capacityBtnNumActive: {
    color: GREEN,
  },
  capacityBtnUnit: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  capacityBtnUnitActive: {
    color: 'rgba(74,222,128,0.6)',
  },
  capacityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  card: {
    backgroundColor: GLASS_BG,
    borderColor: GLASS_BORDER,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
    padding: 18,
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 16,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
  },
  checkIcon: {
    marginLeft: 'auto',
  },
  countBadge: {
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 8,
    borderWidth: 1,
    marginLeft: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  countBadgeText: {
    color: GREEN,
    fontSize: 11,
    fontWeight: '800',
  },
  counterBtn: {
    alignItems: 'center',
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 12,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  counterBtnDisabled: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.07)',
  },
  counterRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  counterValue: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginHorizontal: 32,
    minWidth: 40,
    textAlign: 'center',
  },
  customBtn: {
    alignItems: 'center',
    backgroundColor: GLASS_BG,
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 13,
  },
  customBtnText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 14,
    fontWeight: '600',
  },
  customInputWrap: {
    gap: 0,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  emptyText: {
    color: 'rgba(255,255,255,0.25)',
    fontSize: 14,
    marginTop: 12,
  },
  fieldLabel: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  fieldLabelSpaced: {
    marginTop: 16,
  },
  iconCircle: {
    alignItems: 'center',
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 10,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  modalBox: {
    backgroundColor: 'rgba(3,15,9,0.97)',
    borderColor: 'rgba(74,222,128,0.2)',
    borderRadius: 20,
    borderWidth: 1,
    maxWidth: 400,
    padding: 20,
    width: '85%',
  },
  modalOption: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    marginBottom: 6,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  modalOptionActive: {
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderWidth: 1,
  },
  modalOptionText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 15,
    fontWeight: '500',
  },
  modalOptionTextActive: {
    color: GREEN,
    fontWeight: '700',
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.75)',
    flex: 1,
    justifyContent: 'center',
  },
  modalTitle: {
    borderBottomColor: 'rgba(74,222,128,0.12)',
    borderBottomWidth: 1,
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 14,
    paddingBottom: 12,
  },
  removeBtn: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 140,
  },
  sectionTitle: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  summaryCapacity: {
    color: GREEN,
    fontSize: 22,
    fontWeight: '800',
  },
  summaryCapacityBlock: {
    alignItems: 'flex-end',
  },
  summaryCapacityLabel: {
    color: 'rgba(74,222,128,0.6)',
    fontSize: 11,
    marginTop: 2,
  },
  summaryCard: {
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  summaryCount: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 2,
  },
  summaryLabel: {
    color: 'rgba(74,222,128,0.7)',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textInput: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    color: '#FFFFFF',
    fontSize: 15,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  truckCapacity: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    marginTop: 2,
  },
  truckCard: {
    backgroundColor: GLASS_BG,
    borderColor: GLASS_BORDER,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 10,
    padding: 14,
  },
  truckCardRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  truckIconCircle: {
    alignItems: 'center',
    backgroundColor: GREEN_BG,
    borderColor: GREEN_BORDER,
    borderRadius: 10,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  truckInfo: {
    flex: 1,
  },
  truckNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  truckType: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  typeSelector: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  typeSelectorText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
});
